apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox-pod
  labels:
    name: tech4dev
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "while true; do date > /data/date.html; sleep 10; done"]
    volumeMounts:
    - name: shared-data
      mountPath: /data
    resources:
      requests:
        memory: "32Mi"
        cpu: "100m"
      limits:
        memory: "64Mi"
        cpu: "200m"