apiVersion: v1
kind: Pod
metadata:
  name: limited-resource-pod
  namespace: limited-resources
  labels:
    name: tech4dev
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "400m"
        memory: "400Mi"
      limits:
        cpu: "800m"
        memory: "800Mi"