apiVersion: v1
kind: LimitRange
metadata:
    name: default-limits
    namespace: limited-resources
    labels:
        name: tech4dev
spec:
    limits:
        - type: Container
          default:
              cpu: "500m"
              memory: "512Mi"
          defaultRequest:
              cpu: "800m"
              memory: "656Mi"
