apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  labels:
    name: tech4dev
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh", "-c", "env; cat /etc/app/config/app.properties; sleep 3600"]
    env:
    - name: DATABASE_HOST
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: DATABASE_HOST
    - name: DATABASE_PORT
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: DATABASE_PORT
    - name: APP_COLOR
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_COLOR
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DATABASE_USER
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DATABASE_PASSWORD
    volumeMounts:
    - name: config
      mountPath: /etc/app/config
    resources:
      requests:
        memory: "32Mi"
        cpu: "100m"
      limits:
        memory: "64Mi"
        cpu: "200m"
  volumes:
  - name: config
    configMap:
      name: app-config
      items:
      - key: app.properties
        path: app.properties